Replace nightshade pg cronjob with ome.postgresql_backup
ome/prod-playbooks pull request #285
Opened 2020-09-16 17:35 UTC by manics

Recently we discovered the current pgdump directory format may lead to loss of a the previous backup if an error occurs during the current backup.

This replaces the custom cron job with the ome.postgresql_backup role

Note this role dumps all databases

2020-09-17 06:45 UTC, sbesson commented
Should `templates/nightly-pg_dump-omero.sh.j2` be dropped as well? Looking at

https://github.com/ome/prod-playbooks/blob/b04fb682f988dd0931d187f569bbe451661d6458/templates/nightly-pg_dump-omero.sh.j2#L4-L5

vs

https://github.com/ome/ansible-role-postgresql-backup/blob/3c2ccc78bd69b45f0cd4d5893e3e0a059a48d578/templates/etc-crond-postgresql-backup.j2#L4-L5

the major difference is the usage of `pg_dumpall` which unfortunately does not allow parallel dump. Do we foresee any issue associated with this?

2020-09-17 08:20 UTC, manics commented
I was going to remove it but it's also used on demo, though only to dump to `/tmp` https://github.com/ome/prod-playbooks/blob/b04fb682f988dd0931d187f569bbe451661d6458/ome-demoserver.yml#L378 so I thought I'd deal with nightshade first.

I'd expect the dump to take longer to run without any parallel options, but since it's non-interactive that shouldn't matter.

2020-09-17 08:49 UTC, manics commented
Note Travis is failing:
```
    RUNNING HANDLER [ome.omero_common : restart omero-server] **********************

    fatal: [ome-dundeeomero.openmicroscopy.org]: FAILED! => {"changed": false, "msg": "Unable to restart service omero-server: Job for omero-server.service failed because a timeout was exceeded. See \"systemctl status omero-server.service\" and \"journalctl -xe\" for details.\n"}
```

2020-09-17 15:19 UTC, manics commented
I think the failure was because the molecule test uses `/tmp` as the pg backup dir, but it changed the owner to `postgres` which caused OMERO to fail as it couldn't write to `/tmp`

2020-09-21 19:54 UTC, sbesson commented
:+1: for replacing custom tasks by an existing role. As a point of comparision in terms of performance, on `pub-omero`,

```
bash-4.2$ time pg_dump -j 4 -Fd -f /tmp/20200922_pg_dump_omero.dir/ omero

real	0m34.009s
user	1m6.756s
sys	0m1.188s
bash-4.2$ time pg_dumpall -f /tmp/20200922_pg_dumpall

real	0m34.115s
user	0m3.686s
sys	0m4.543s
```

For the functional testing, my proposal would be to add similar changes against `ome-demoserver.yml`, deploy them against `pub-omero` and test a database recovery scenario using the DB dump.

2020-10-12 13:19 UTC, manics commented
I've made the same changes to the demo playbook

2020-10-16 10:57 UTC, sbesson commented
With the systems back up and running, now deploy to `pub-omero.openmicroscopy.org` for internal testing. Proposed next steps:

- check that the daily DB dump is created in the expected place
- test a DB restore on `pub-omero`
- propagate the changes to the production systems `demo` + `ome-dundeeomero`

2020-10-19 14:28 UTC, sbesson requested changes
As noted this morning, a side effect of https://github.com/ome/prod-playbooks/pull/285#issuecomment-709976471 has been to fill the `/tmp/` partition with daily 3G backups.

Next action will be to update the default backup dir to use the `/OMERO` partition or another mount which can accommodate 20-25G of dumps.

2020-10-20 09:09 UTC, sbesson commented
Deleted the previous backups on `/tmp/pgbackup/` of `pub-omero`. This inspired me a related thought: at the moment, the vanilla output of the backup role are uncompressed dumps. Is there an easy way to enable compression?

2020-10-20 12:36 UTC, manics commented
I've updated this PR to use https://github.com/ome/ansible-role-postgresql-backup/pull/5, `pub-omero` has been updated

2020-10-21 10:08 UTC, sbesson commented
Looks good after the first execution on `pub-omero`

```
[root@pub-omero sbesson]# du -csh /OMERO/pgbackup/*
404M	/OMERO/pgbackup/nightly-omero-Wed.pgdump.gz
404M	total
```

I'll leave the cron job to run ~5-7 days of rolling backups and then test a full restore early next week.

2021-01-17 22:04 UTC, sbesson requested changes
Once the requirements file is updated to use the new role release, proposing to schedule the deployment of this playbook on the various target servers

2021-01-17 22:04 UTC, sbesson commented on requirements.yml
> +- name: ome.postgresql_backup
This can be updated to `ome.postgresql_backup 0.2.0` which has been released with compression support.

2021-01-19 23:24 UTC, sbesson approved these changes
Thanks @manics. Now deployed on both demo servers for confirmation tomorrow. I will deploy on `ome-dundeeomero` tomorrow evening if no issue is found with the dump logic

2021-01-20 20:04 UTC, merged

2021-01-20 20:27 UTC, sbesson commented
Deployed on `ome-dundeeomero.openmicroscopy.org`