Django upgrade
ome/prod-playbooks pull request #335
Opened 2022-03-22 17:17 UTC by pwalczysko

cc @sbesson 

the changes are on top of https://github.com/ome/prod-playbooks/pull/334

Deployed successfully on ome-training-3

Possibly there is a change in ``mapr`` in between ?
This here is a status from couple of days ago, with RC on mapr.

2022-03-23 16:16 UTC, sbesson requested changes

2022-03-23 16:16 UTC, sbesson commented on omero/training-server/playbook.yml
> +    omero_web_release: "{{ omero_web_release_override | default('5.14.0.rc1') }}"
```suggestion
    omero_web_release: "{{ omero_web_release_override | default('5.14.0') }}"
```

2022-03-23 17:27 UTC, pwalczysko commented
@sbesson thank you, changes applied as requested.
This is now applied on ``ome-training-3``
All works there, including mapr, parade, webtagging, tagsearch.
Checked the compliancy with the versions in this notebook

```
(venv3) [pwalczysko@ome-training-3 ~]$ pip freeze | grep web
omero-web==5.14.0
omero-webtagging-autotag==3.2.0
omero-webtagging-tagsearch==3.2.0
(venv3) [pwalczysko@ome-training-3 ~]$ pip freeze | grep mapr
omero-mapr==0.5.0
```

2022-03-23 17:35 UTC, sbesson approved these changes
Looks good and very straightforward. Happy for these changes to get deployed onto all training servers.

@jburel  should we capture the upgrade of the other UoD OMERO deployments as issues?

2022-03-24 15:11 UTC, pwalczysko commented
This is now deployed on all 4 training servers. All works as expected.
Note that the manual delete of the ``...omero`` file was performed in each server.

```
cd /opt/omero/web/config/
sudo rm -rf omero-web-outreach-webapps.omero
```

2022-03-24 15:17 UTC, merged